### ISSUE TITLE
could not find `CommunicationError` in `error`

### ISSUE THREAD

**Issue by flip111** [0xSiO/bolt-rs#11]
```
error[E0433]: failed to resolve: could not find `CommunicationError` in `error`
  --> /home/flip111/.cargo/registry/src/github.com-1ecc6299db9ec823/bolt-client-0.9.1/src/client/v1.rs:26:5
   |
26 |     #[bolt_version(1, 2)]
   |     ^^^^^^^^^^^^^^^^^^^^^ could not find `CommunicationError` in `error`
   |
   = note: this error originates in the attribute macro `bolt_version` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Not sure how to fix this. Possibly a bug in this library ?

rustc 1.57.0 (f1edd0429 2021-11-29)

**Comment by 0xSiO** [comment]
Thanks for finding this @flip111, there was a breaking change in `bolt-client-macros` v0.2.2. I've made the following changes:
- Republished `bolt-client-macros` v0.2.2 as v0.3.0
- Published `bolt-client` v0.10.1, which depends on `bolt-client-macros` v0.3.0
- Yanked `bolt-client-macros` v0.2.2 and `bolt-client` v0.10.0
