### ISSUE TITLE
Appear Error "IO driver has terminated", How to solve

### ISSUE THREAD

**Issue by pengyizeng** [0xSiO/bolt-rs#13]
Recently, I try "neo4rs"," Deadpool-bolt", "b88-bolt" to create connection pool with neo4j. My program appears

"error:UnexpectedMessage("unexpected response for RUN: Err(IOError { detail: "IO driver has terminated" })")"driver has terminated"

when many query appears in a short time. How to solve it ?

I have google the error , but I did not found any useful information.

**Comment by 0xSiO** [comment]
Hi @pengyizeng, could you provide a minimal example using my libraries that reproduces this problem? I also saw your discussion [here](https://github.com/tokio-rs/tokio/discussions/4420) and I'm wondering if you might be using the tokio runtime in an unintended way.
