### ISSUE TITLE
Serde Serialization/Deserialization

### ISSUE THREAD

**Issue by Illusivebyte** [0xSiO/bolt-rs#15]
Currently there does not appear to be an easy way to serialize the Record structs and the Values they contain. My current work around is to manually convert the Bolt Values to Serde JSON Values, but it seems a bit clunky. I believe adding support for serialization/deserialization with Serde would be beneficial to this library.

**Comment by 0xSiO** [comment]
See [this comment](https://github.com/0xSiO/bolt-rs/pull/14#issuecomment-1125590804).

**Comment by Illusivebyte** [comment]
Got it! The application I am building is going to be handling data in a way where I will not know its structure ahead of time (other than nodes and relationships). I believe I can work around it with my current approach but I still think this would be a great feature.
