### ISSUE TITLE
usage example

### ISSUE THREAD

**Issue by againstplag2022** [0xSiO/bolt-rs#16]
Thank you very much for open sourcing this. This is definitely useful. Is it possible that a usage example being provided for this library?
I tried to make the [example](https://docs.rs/bolt-client/latest/bolt_client/) here to work, but keep getting errors like the following:
```
let stream = BufStream::new(stream).compat();
    |                  -------------- ^^^^^^ the trait `std::io::Read` is not implemented for `bolt_client::Stream`
    |                  |
    |                  required by a bound introduced by this call

```
currently I have this in my cargo.toml file:
```tokio = { version = "1", features = ["full"] }
bufstream = "0.1"
bolt-client = {version = "0.10.0", features = ["tokio-stream"]}
```

and I have imports like this:
```extern crate bolt_client;
use bolt_client::*;
use bufstream::BufStream;
use bolt_proto::{message::*, value::*, version::*, Message, Value};
```

Not sure whether my cargo or import statements are correct. Would be great if a full example can be provided.

**Comment by timshoaf** [comment]
Have you:  `use tokio_util::compat::*;` ?

**Comment by againstplag2022** [comment]
yeah, same error

**Comment by againstplag2022** [comment]
the following worked for testing:

```
[dependencies]
tokio = { version = "1.14.0", features = ["full"] }
bolt-client = {version = "0.10.1", features =["tokio-stream"]}

[dev-dependencies.tokio-util]
features = ["compat"]
version = "0.6.0" 
```
and importing like the original example.

**Comment by 0xSiO** [comment]
Hey @againstplag2022,
These libraries use asynchronous I/O, so you can't use synchronous I/O libraries like [bufstream](https://crates.io/crates/bufstream). The `Stream` struct I've provided via the `tokio-stream` feature implements the [AsyncRead](https://docs.rs/tokio/1.14.0/tokio/io/trait.AsyncRead.html) and [AsyncWrite](https://docs.rs/tokio/1.14.0/tokio/io/trait.AsyncWrite.html) traits, and you can wrap it in a tokio [BufStream](https://docs.rs/tokio/1.14.0/tokio/io/struct.BufStream.html) as in the [example](https://docs.rs/bolt-client/latest/bolt_client/index.html#example).

However, if you're working on an application and you just need a way to easily get connections to your database, you should be using a connection pool instead, like [deadpool](https://crates.io/crates/deadpool), [bb8](https://crates.io/crates/bb8), or [mobc](https://crates.io/crates/mobc). I've published adapter crates for each of those three libraries. [Here's an example](https://github.com/flip111/deadpool_bolt_example/blob/75325a387724fe515fa6f4cd562cb8e1ff71d681/src/main.rs) of what using a connection pool might look like for a web application.

Let me know if you have any other questions!
