### ISSUE TITLE
Question: How Connect to a Neo4j Cluster?

### ISSUE THREAD

**Issue by ajosecueto** [0xSiO/bolt-rs#17]
i found an issue updated at 2021, i would like to use ROUTE with deadpool bolt: [(https://docs.rs/bolt-client/latest/bolt_client/struct.Client.html#method.route)]
Can you provide an example of how to use it with a cluster?
Thanks.

**Comment by 0xSiO** [comment]
I haven't implemented support for Neo4j clustering - that'll probably be a feature of the upcoming [higher-level driver](https://github.com/0xSiO/neo4j-rs). If we assume a simple setup with 1 primary and several secondaries, and you want a way to get a connection pool to your primary server and then a list of connection pools for your read replicas, you could use the following approach, though it's probably not ideal:

1. Connect to your primary server and create a pool using the approach in the [deadpool-bolt](https://docs.rs/deadpool-bolt) example. You can use this pool for reads and writes.
2. Grab a list of your read replicas by calling [`route`](https://docs.rs/bolt-client/0.11.0/bolt_client/struct.Client.html#method.route) on a connection from your primary pool. Use the list of IP addresses in the response to create a connection pool for each read replica, using the same approach as in step 1.
3. Distribute reads across your read replicas using whatever strategy you wish.

Note that I haven't tested this approach, and it doesn't account for things like multiple primaries or a routing table that changes over time - you'll have to handle those yourself if that's your use case. More details on clustering and the routing table [here](https://neo4j.com/docs/bolt/current/driver-api/#_neo4j_4_0_cluster_and_multiple_databases).

**Comment by ajosecueto** [comment]
Thanks for your detailed answer, I would try to implement it.

For example when I create the first pool and then get all the read replicas. I would store all these new pools in an Vec and the use something like a load balancer or round robin for each request. 

I will be use a neo4j cluster o memgraph cluster
