### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by NoahPN** [0xSiO/bolt-rs#18]
Hi mate,
I am Noah, a Rust developer, and I am trying to reach out to you to ask you something about the crate `atmos` that you own. Please reply at dev@noahpn.io that would really mean a lot to me and my project.
Thanks in advance,
Noah <dev@noahpn>

**Comment by 0xSiO** [comment]
Hey @noahpnio, I plan on using `atmos` and my other space/physics-themed crate names in my future projects. Sorry for the inconvenience
