### ISSUE TITLE
Neo4j 4 support

### ISSUE THREAD

**Issue by John0x** [0xSiO/bolt-rs#2]
Hey, I'm currently researching a new tech stack for a new project and bolt-rs seems to be the only active library for rust->neo4j.

Is there a rough ETA on support for the newest Neo4j version (4)?
Would be great to be able to use Rust for a real life project

**Comment by 0xSiO** [comment]
Hey @John0x, the next release of the libraries should support Bolt v3 and Neo4j 4.0. After that I will work on supporting Bolt v4. Currently there's no official documentation for newer versions of the protocol so I'm building it by referencing the official drivers and through trial & error. ~~I'd say the next release should be within 1-2 months assuming I can find time to work on it.~~

**Comment by 0xSiO** [comment]
I decided to go ahead and power through this today, and it took a lot less time than I initially thought. The latest build of master (6f18e90) now supports Neo4j 4.0, although most of the new functionality is not yet documented. I'll be updating the documentation and pushing out a new release soon, probably this week.

**Comment by John0x** [comment]
Wow, thank you dude :) 
I'll go ahead and take it for a test later. 

You helped a lot, thanks 👍
