### ISSUE TITLE
QUESTION: how to connect to a different database

### ISSUE THREAD

**Issue by ajosecueto** [0xSiO/bolt-rs#21]
Actually we are connecting to the default database "neo4j" but we would like to other database because we are using an neo4j cluster and logically we are splitting the databases.

**Comment by 0xSiO** [comment]
Several `Client` methods, (for example, [`run`](https://docs.rs/bolt-client/0.11.0/bolt_client/struct.Client.html#method.run)) allow you to pass a `db` entry in the `metadata` parameter, which specifies the name of the database to use.
