### ISSUE TITLE
Question: Is this bb8 implementation mature enough to use in a production environment with newer version of neo4j (5.19.0)

### ISSUE THREAD

**Issue by 0xd-0** [0xSiO/bolt-rs#23]
Greetings,

I stumbled on this bb8 implementation and haven't seen recent activity on crate. Is this project still compatible with newer version of neo/bolt? I appreciate the feedback, I'm looking to use this in a production environment.

**Comment by 0xSiO** [comment]
This project has been tested with versions of Bolt up to v4.4. See the [compatibility matrix](https://neo4j.com/docs/bolt/current/bolt-compatibility/) for which versions of Neo4j are supported - according to that chart, it seems like Neo4j 5.19 should work fine using Bolt 4.4. I will update the project to newer versions of the protocol once I have spare time to work on this. There probably won't be any major changes in the near future, so I would consider this stable enough to use in production.

**Comment by 0xd-0** [comment]
Thank you for the quick reply. I successfully integrated and tested using 4.4 with axum nested state (w/redis) and it connected. A quick comment on the Manager struct for those of us using multiple bb8 pools, it would be beneficial to rename this to BoltManager or something more descriptive (useful in type inference in the IDE) when I see multiple bb8 pool types i.e. Pool<>, etc.

Thanks again.
