### ISSUE TITLE
Production-readiness and contributions

### ISSUE THREAD

**Issue by clarkenciel** [0xSiO/bolt-rs#3]
Hi! This family of crates looks great and I have a couple of questions about your "production readiness" warnings:

- What work needs to be done to consider it "production ready?"
- What help do you need to achieve that state?

I'd love to be able to use this in some smaller projects for my day job and am looking to help out in any way I can. Thanks again for all the work you've done for this!

**Comment by 0xSiO** [comment]
Hi @clarkenciel, thanks for your interest in this project!

The main tasks to finish are supporting Bolt v4, addressing some of the issues marked by TODO comments, and maybe improving the testing infrastructure a bit.

From what I gather after skimming the official driver source, v4 messaging uses a v2 value packer/unpacker (which is good news, no need to add more values) and a modified v3 message packer/unpacker, with 2 new message types that replace the v1 DiscardAll/PullAll messages.

There is also the new workflow to consider when it comes to querying, much of it is described [here](https://neo4j.com/docs/driver-manual/current/cypher-workflow/), but there's probably more surprises in the official source (protocol documentation [doesn't seem to be a big priority](https://github.com/neo4j/neo4j/issues/12361) for the folks at Neo4j). The client API would need to account for these changes if necessary.

Other than that, though, if you're using the libraries for Bolt v1-v3 servers, I would say it's pretty much production-ready (minus the things I mentioned above). I'll try to find some time to work on Bolt v4 this week.

**Comment by clarkenciel** [comment]
Thanks for getting back to me! I think I'll try to focus on the querying workflow; sessions and causal querying would be pretty crucial to my immediate needs for a neo4j library.

**Comment by 0xSiO** [comment]
Thanks, but keep in mind this is not a Neo4j-specific project and I'd like all features to be general across any server that implements the Bolt protocol. Causal chaining appears to be a Neo4j-specific feature that uses the metadata of Bolt messages to pass bookmarks around. It's clear that all Bolt v3+ servers should support transactions via BEGIN / COMMIT / ROLLBACK, but I'm still thinking about to what extent I want to implement higher-level handling of these transactions in the client. My [next project](https://github.com/lucis-fluxum/neo4j-rs) to follow this one will be a higher-level library that fills in all the Neo4j-specific features.

**Comment by 0xSiO** [comment]
All tasks have now been addressed by the latest set of releases.
