### ISSUE TITLE
Question: Bolt v4 doc?

### ISSUE THREAD

**Issue by aphorisme** [0xSiO/bolt-rs#5]
Hello! 
This might be the wrong channel for a meta question, but I didn't find any other possibility to contact you. Did you reverse engineer the bolt version 4 specs? Or do you have any official source?

Thanks in advance!

**Comment by 0xSiO** [comment]
Hello,

After looking through the [official driver source](https://github.com/neo4j/neo4j-java-driver), I found that Bolt v4 added two new messages on top of Bolt v3, DISCARD and PULL. Their usage is documented in the [v4 client tests](https://github.com/lucis-fluxum/bolt-rs/blob/master/bolt-client/src/client/v4.rs#L134-L176) as well as the first [client example](https://docs.rs/bolt-client/0.7.0/bolt_client/). There aren't any new data types in Bolt v4, as far as I know.

Looks like Neo4j has also started working on version 4.1 of the protocol, so there will be more changes to come.

**Comment by aphorisme** [comment]
Thanks a lot for your answer! : )
