### ISSUE TITLE
Connect to a Neo4j Cluster 

### ISSUE THREAD

**Issue by ppoliani** [0xSiO/bolt-rs#9]
Does the bolt client support routing so it can be used to connect to a Neo4j cluster?

**Comment by 0xSiO** [comment]
Nope, this requires a driver that makes Neo4j-specific procedure calls to fetch the routing table, [among other things](https://7687.org/driver_api/driver-api-specification.html#client-side-routing). Supporting specific Neo4j features is not a goal of this project, but definitely something I'll add to my higher-level Neo4j driver once I get around to it.

**Comment by ppoliani** [comment]
Oh I see; yes that makes sense. Will the Neo4j driver be hoated on a separate repo?

**Comment by 0xSiO** [comment]
It'll be hosted [here](https://github.com/lucis-fluxum/neo4j-rs). Still thinking about the design I want for that library... will start working on that once I have the time.

**Comment by 0xSiO** [comment]
Update to this old question - Bolt v4.3 introduces the [`ROUTE`](https://7687.org/bolt/bolt-protocol-message-specification-4.html#request-message---43---route) message, so fetching routing info _is_ supported now. Support for v4.3 is in the current master and will be released soon.
